### ISSUE TITLE
Delete already added label in BM host CR

### ISSUE THREAD

**Issue by digambar15** [metal3-io/hardware-classification-controller#6] opened 2020-05-04 12:58 UTC
There is one noticed in our testing that if user by mistake forgot to configure right Hardware parameters and applied profile ABC using kubectl, so HCC proceesed profile ABC and add labels on matches hosts. 
After sometime, by looking at profile ABC, user realized that he has to do different configuration. In this case, if user does change in same profile ABC by configuring right HW params and process it. 

HCC should delete labels from existing hosts first and classify hosts based on new configuration provided and add label to matches hosts.

Please let me know if you are agree with the above workflow for deleting label feature.
Or
Let us know your approach in this case.

T

**Comment by dhellmann** [comment] 2020-05-05 14:10
As I tried to express in the original design review for HCC, I think we want HCC to focus on reconciling hosts rather than profiles. Each time through the reconcile method, HCC should build the set of classification labels that apply to a host and if they are different from the ones on the host currently the host can be updated. That eliminates any need to implement add & remove logic and ensures that updates to hosts are atomic.

**Comment by digambar15** [comment] 2020-05-06 17:08
Yes Doug. We have done latest implementation by adding watch on HWCC. Request you to go through latest PR. This certainly resolved this issue :)

**Comment by nehaalhat** [comment] 2020-07-27 12:17
This issue is fixed in PR: https://github.com/metal3-io/hardware-classification-controller/pull/29

**Comment by sumitjadhav1** [comment] 2020-09-10 17:35
Already added label get deleted if we apply the same profile with non-matching configuration.
The issue is fixed and verified. Can be closed.

@digambar15 You're the owner, please mark it closed.

**Comment by digambar15** [comment] 2020-09-14 05:39
Yes. Thanks for completing the testing! Good to close now!

**Closed as completed** 2020-09-14 05:39 UTC
Labels: kind/feature
